### ISSUE TITLE
Enable Future Action cause "Save Changes" notification

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Future#449]
When enabling future action, upon updating the post/page there will be notification to save changes. More detail on this video:

https://github.com/publishpress/PublishPress-Future/assets/83811723/7b5223ff-8024-4d0f-ba21-fd37104734e6

Normal behavior:

https://github.com/publishpress/PublishPress-Future/assets/83811723/1bbc20b9-71ce-4efc-bf6b-3468471b9e24

# Subtasks

* [x] Fix the notification displayed when post data was not changed yet.
* [x] Double check new issue happening when a date is selected for the future action and the post publishing date is changing as well.
* [x] Double check support to custom post types
* [x] Fix the "No terms" that is always visible.

**Comment by stevejburge** [comment]
Here's another example on a new site. I schedule a post and save everything correctly.

Future still causes a prompt that I've forgotten something:

<img width="1132" alt="Screenshot 2023-06-20 at 11 25 09 AM" src="https://github.com/publishpress/PublishPress-Future/assets/3868028/70b40bd8-f678-4af8-93eb-f26bcad6fff4">
<img width="549" alt="Screenshot 2023-06-20 at 11 25 32 AM" src="https://github.com/publishpress/PublishPress-Future/assets/3868028/0b0dc768-7147-48dc-972d-b01a75af543e">

**Comment by marco910** [comment]
I'm experiencing the same as described by @stevejburge .

When clicking on the WordPress logo on the top left after saving the post and waiting for a few seconds, I get the browser default prompt that there are unsaved changes.
